from __future__ import annotations

import csv
import hashlib
import html
import json
import re
import shutil
from datetime import datetime, timezone
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .scanner import read_text


GENERATED_BY = "anti-silo ingest"
DEFAULT_INGEST_EXTENSIONS = {
    ".md",
    ".txt",
    ".csv",
    ".json",
    ".html",
    ".htm",
    ".docx",
    ".xlsx",
    ".pdf",
}


@dataclass(frozen=True)
class ExtractionResult:
    text: str
    status: str = "complete"
    note: str = ""


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _safe_name(rel_path: Path) -> str:
    stem = "__".join(rel_path.with_suffix("").parts)
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", stem).strip("._-")
    return f"{stem or 'source'}.md"


def _excluded(rel_path: Path, config: dict[str, Any]) -> bool:
    excluded = set(config.get("exclude_dirs", []))
    parts = set(rel_path.parts)
    return bool(parts & excluded)


def _prepare_output(source_root: Path, output_vault: Path) -> None:
    source_root = source_root.resolve()
    output_vault = output_vault.resolve()
    if output_vault == source_root:
        raise ValueError("output vault must be different from the source folder")
    if output_vault.exists():
        manifest = output_vault / "SOURCE_MANIFEST.json"
        if not manifest.exists():
            raise ValueError(f"refusing to replace non-ingest folder: {output_vault}")
        data = json.loads(manifest.read_text(encoding="utf-8"))
        if data.get("generated_by") != GENERATED_BY:
            raise ValueError(f"refusing to replace folder not generated by Anti-Silo ingest: {output_vault}")
        shutil.rmtree(output_vault)
    output_vault.mkdir(parents=True, exist_ok=True)


def _extract_csv(path: Path) -> ExtractionResult:
    rows: list[str] = []
    with path.open("r", encoding="utf-8-sig", newline="", errors="replace") as f:
        reader = csv.reader(f)
        for idx, row in enumerate(reader):
            if idx >= 200:
                return ExtractionResult("\n".join(rows), "truncated", "CSV limited to the first 200 rows")
            rows.append(" | ".join(cell.strip() for cell in row))
    return ExtractionResult("\n".join(rows))


def _extract_json(path: Path) -> ExtractionResult:
    with path.open("r", encoding="utf-8-sig", errors="replace") as f:
        data = json.load(f)
    text = json.dumps(data, ensure_ascii=False, indent=2)
    if len(text) > 20000:
        return ExtractionResult(text[:20000], "truncated", "JSON limited to the first 20,000 characters")
    return ExtractionResult(text)


def _strip_html(text: str) -> str:
    text = re.sub(r"(?is)<(script|style).*?>.*?</\1>", " ", text)
    text = re.sub(r"(?s)<[^>]+>", " ", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def _extract_docx(path: Path) -> ExtractionResult:
    try:
        import docx  # type: ignore[import-not-found]
    except Exception as exc:  # pragma: no cover - depends on optional package
        return ExtractionResult("", "failed", f"DOCX extraction unavailable: {exc}")
    document = docx.Document(str(path))
    return ExtractionResult("\n".join(paragraph.text for paragraph in document.paragraphs if paragraph.text.strip()))


def _extract_xlsx(path: Path) -> ExtractionResult:
    try:
        import openpyxl  # type: ignore[import-not-found]
    except Exception as exc:  # pragma: no cover - depends on optional package
        return ExtractionResult("", "failed", f"XLSX extraction unavailable: {exc}")
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    chunks: list[str] = []
    truncated = False
    for sheet in workbook.worksheets:
        chunks.append(f"## Sheet: {sheet.title}")
        for idx, row in enumerate(sheet.iter_rows(values_only=True)):
            if idx >= 200:
                truncated = True
                break
            values = ["" if value is None else str(value) for value in row]
            if any(value.strip() for value in values):
                chunks.append(" | ".join(values))
    workbook.close()
    return ExtractionResult(
        "\n".join(chunks),
        "truncated" if truncated else "complete",
        "XLSX sheets limited to the first 200 rows" if truncated else "",
    )


def _extract_pdf(path: Path) -> ExtractionResult:
    try:
        from pypdf import PdfReader  # type: ignore[import-not-found]
    except Exception as exc:  # pragma: no cover - depends on optional package
        return ExtractionResult("", "failed", f"PDF extraction unavailable: {exc}")
    reader = PdfReader(str(path))
    pages: list[str] = []
    for page in reader.pages[:20]:
        pages.append(page.extract_text() or "")
    return ExtractionResult(
        "\n".join(pages),
        "truncated" if len(reader.pages) > 20 else "complete",
        "PDF limited to the first 20 pages" if len(reader.pages) > 20 else "",
    )


def extract_text(path: Path) -> ExtractionResult:
    ext = path.suffix.lower()
    if ext in {".md", ".txt"}:
        return ExtractionResult(read_text(path))
    if ext == ".csv":
        return _extract_csv(path)
    if ext == ".json":
        return _extract_json(path)
    if ext in {".html", ".htm"}:
        return ExtractionResult(_strip_html(read_text(path)))
    if ext == ".docx":
        return _extract_docx(path)
    if ext == ".xlsx":
        return _extract_xlsx(path)
    if ext == ".pdf":
        return _extract_pdf(path)
    return ExtractionResult("", "failed", "Unsupported file type")


def iter_source_files(source_root: Path, config: dict[str, Any]) -> list[Path]:
    extensions = {ext.lower() for ext in config.get("ingest_extensions", sorted(DEFAULT_INGEST_EXTENSIONS))}
    files: list[Path] = []
    if source_root.is_file():
        return [source_root] if source_root.suffix.lower() in extensions and not source_root.name.startswith("~$") else []
    for path in source_root.rglob("*"):
        if not path.is_file() or path.name.startswith("~$"):
            continue
        rel_path = path.relative_to(source_root)
        if _excluded(rel_path, config):
            continue
        if path.suffix.lower() in extensions:
            files.append(path)
    return sorted(files)


def write_ingest(
    source_root: Path,
    config: dict[str, Any],
    output_vault: Path | None = None,
    source_links: dict[str, Path] | None = None,
) -> dict[str, Any]:
    source_root = source_root.resolve()
    output_vault = (output_vault or (source_root.parent / f"{source_root.name}_anti_silo_staging")).resolve()
    _prepare_output(source_root, output_vault)

    rows: list[dict[str, Any]] = []
    source_links = source_links or {}
    repair_sources = output_vault / "repair_sources"
    by_extension: dict[str, int] = {}
    for source in iter_source_files(source_root, config):
        rel_path = source.relative_to(source_root) if source_root.is_dir() else Path(source.name)
        digest = _sha256(source)
        ext = source.suffix.lower()
        by_extension[ext] = by_extension.get(ext, 0) + 1
        extraction = extract_text(source)
        extracted = extraction.text.strip()
        target = output_vault / _safe_name(rel_path)
        linked_source = source_links.get(rel_path.as_posix())
        linked_digest = _sha256(linked_source) if linked_source and linked_source.is_file() else ""
        intake_metadata = ["intake_kind: self_indexed"]
        claim_text = "claim: extracted document content awaiting independent source verification"
        if linked_digest:
            intake_metadata = ["repair_linked_source: true", f"source_hash: {linked_digest}"]
            claim_text = "claim: extracted document content linked to a user-selected independent source; semantic match not verified"
            repair_sources.mkdir(parents=True, exist_ok=True)
            pointer = repair_sources / f"{linked_digest}.md"
            if not pointer.exists():
                pointer.write_text(
                    "\n".join(
                        [
                            "type: user_selected_source",
                            "source_of_truth: true",
                            f"raw_source_hash: {linked_digest}",
                            f"source_name: {json.dumps(linked_source.name, ensure_ascii=False)}",
                            "---",
                            "source-of-truth: user-selected independent local file; semantic match not verified",
                            "",
                        ]
                    ),
                    encoding="utf-8",
                )
        target.write_text(
            "\n".join(
                [
                    "type: extracted_source_document",
                    "claim_kind: synthesis",
                    *intake_metadata,
                    f"extraction_status: {extraction.status}",
                    f"extraction_note: {json.dumps(extraction.note, ensure_ascii=False)}",
                    f"intake_hash: {digest}",
                    f"source_file: {json.dumps(rel_path.as_posix(), ensure_ascii=False)}",
                    f"source_extension: {ext}",
                    "---",
                    f"source-of-truth: local intake copy from `{rel_path.as_posix()}`; not independent evidence",
                    claim_text,
                    "",
                    extracted or "[no extractable text]",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        rows.append(
            {
                "source_file": rel_path.as_posix(),
                "staged_file": target.relative_to(output_vault).as_posix(),
                "extension": ext,
                "raw_source_hash": digest,
                "bytes": source.stat().st_size,
                "extraction_status": extraction.status,
                "extraction_note": extraction.note,
                "linked_source": linked_source.name if linked_digest and linked_source else "",
            }
        )

    payload = {
        "generated_by": GENERATED_BY,
        "generated": datetime.now(timezone.utc).isoformat(),
        "source_root": str(source_root),
        "output_vault": str(output_vault),
        "files": len(rows),
        "by_extension": by_extension,
        "rows": rows,
    }
    (output_vault / "SOURCE_MANIFEST.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    md = ["# Anti-Silo Source Intake", "", f"- source root: `{source_root}`", f"- files staged: **{len(rows)}**", ""]
    for ext, count in sorted(by_extension.items()):
        md.append(f"- `{ext}`: {count}")
    (output_vault / "SOURCE_INTAKE.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    return payload
