from __future__ import annotations

import csv
import hashlib
import html
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .scanner import read_text


GENERATED_BY = "anti-silo ingest"
DEFAULT_INGEST_EXTENSIONS = {
    ".md",
    ".txt",
    ".csv",
    ".json",
    ".html",
    ".htm",
    ".docx",
    ".xlsx",
    ".pdf",
}


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _safe_name(rel_path: Path) -> str:
    stem = "__".join(rel_path.with_suffix("").parts)
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", stem).strip("._-")
    return f"{stem or 'source'}.md"


def _excluded(rel_path: Path, config: dict[str, Any]) -> bool:
    excluded = set(config.get("exclude_dirs", []))
    parts = set(rel_path.parts)
    return bool(parts & excluded)


def _prepare_output(source_root: Path, output_vault: Path) -> None:
    source_root = source_root.resolve()
    output_vault = output_vault.resolve()
    if output_vault == source_root:
        raise ValueError("output vault must be different from the source folder")
    if output_vault.exists():
        manifest = output_vault / "SOURCE_MANIFEST.json"
        if not manifest.exists():
            raise ValueError(f"refusing to replace non-ingest folder: {output_vault}")
        data = json.loads(manifest.read_text(encoding="utf-8"))
        if data.get("generated_by") != GENERATED_BY:
            raise ValueError(f"refusing to replace folder not generated by Anti-Silo ingest: {output_vault}")
        shutil.rmtree(output_vault)
    output_vault.mkdir(parents=True, exist_ok=True)


def _extract_csv(path: Path) -> str:
    rows: list[str] = []
    with path.open("r", encoding="utf-8-sig", newline="", errors="replace") as f:
        reader = csv.reader(f)
        for idx, row in enumerate(reader):
            if idx >= 200:
                rows.append("[truncated after 200 rows]")
                break
            rows.append(" | ".join(cell.strip() for cell in row))
    return "\n".join(rows)


def _extract_json(path: Path) -> str:
    with path.open("r", encoding="utf-8-sig", errors="replace") as f:
        data = json.load(f)
    return json.dumps(data, ensure_ascii=False, indent=2)[:20000]


def _strip_html(text: str) -> str:
    text = re.sub(r"(?is)<(script|style).*?>.*?</\1>", " ", text)
    text = re.sub(r"(?s)<[^>]+>", " ", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def _extract_docx(path: Path) -> str:
    try:
        import docx  # type: ignore[import-not-found]
    except Exception as exc:  # pragma: no cover - depends on optional package
        return f"[docx extraction unavailable: {exc}]"
    document = docx.Document(str(path))
    return "\n".join(paragraph.text for paragraph in document.paragraphs if paragraph.text.strip())


def _extract_xlsx(path: Path) -> str:
    try:
        import openpyxl  # type: ignore[import-not-found]
    except Exception as exc:  # pragma: no cover - depends on optional package
        return f"[xlsx extraction unavailable: {exc}]"
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    chunks: list[str] = []
    for sheet in workbook.worksheets:
        chunks.append(f"## Sheet: {sheet.title}")
        for idx, row in enumerate(sheet.iter_rows(values_only=True)):
            if idx >= 200:
                chunks.append("[sheet truncated after 200 rows]")
                break
            values = ["" if value is None else str(value) for value in row]
            if any(value.strip() for value in values):
                chunks.append(" | ".join(values))
    workbook.close()
    return "\n".join(chunks)


def _extract_pdf(path: Path) -> str:
    try:
        from pypdf import PdfReader  # type: ignore[import-not-found]
    except Exception as exc:  # pragma: no cover - depends on optional package
        return f"[pdf extraction unavailable: {exc}]"
    reader = PdfReader(str(path))
    pages: list[str] = []
    for page in reader.pages[:20]:
        pages.append(page.extract_text() or "")
    if len(reader.pages) > 20:
        pages.append("[truncated after 20 pages]")
    return "\n".join(pages)


def extract_text(path: Path) -> str:
    ext = path.suffix.lower()
    if ext in {".md", ".txt"}:
        return read_text(path)
    if ext == ".csv":
        return _extract_csv(path)
    if ext == ".json":
        return _extract_json(path)
    if ext in {".html", ".htm"}:
        return _strip_html(read_text(path))
    if ext == ".docx":
        return _extract_docx(path)
    if ext == ".xlsx":
        return _extract_xlsx(path)
    if ext == ".pdf":
        return _extract_pdf(path)
    return "[unsupported file type]"


def iter_source_files(source_root: Path, config: dict[str, Any]) -> list[Path]:
    extensions = {ext.lower() for ext in config.get("ingest_extensions", sorted(DEFAULT_INGEST_EXTENSIONS))}
    files: list[Path] = []
    if source_root.is_file():
        return [source_root] if source_root.suffix.lower() in extensions and not source_root.name.startswith("~$") else []
    for path in source_root.rglob("*"):
        if not path.is_file() or path.name.startswith("~$"):
            continue
        rel_path = path.relative_to(source_root)
        if _excluded(rel_path, config):
            continue
        if path.suffix.lower() in extensions:
            files.append(path)
    return sorted(files)


def write_ingest(source_root: Path, config: dict[str, Any], output_vault: Path | None = None) -> dict[str, Any]:
    source_root = source_root.resolve()
    output_vault = (output_vault or (source_root.parent / f"{source_root.name}_anti_silo_staging")).resolve()
    _prepare_output(source_root, output_vault)

    rows: list[dict[str, Any]] = []
    by_extension: dict[str, int] = {}
    for source in iter_source_files(source_root, config):
        rel_path = source.relative_to(source_root) if source_root.is_dir() else Path(source.name)
        digest = _sha256(source)
        ext = source.suffix.lower()
        by_extension[ext] = by_extension.get(ext, 0) + 1
        extracted = extract_text(source).strip()
        target = output_vault / _safe_name(rel_path)
        target.write_text(
            "\n".join(
                [
                    "type: extracted_source_document",
                    "claim_kind: synthesis",
                    "source_of_truth: true",
                    f"source_hash: {digest}",
                    f"raw_source_hash: {digest}",
                    f"source_file: {json.dumps(rel_path.as_posix(), ensure_ascii=False)}",
                    f"source_extension: {ext}",
                    "---",
                    f"source-of-truth: extracted from local source file `{rel_path.as_posix()}`",
                    "claim: extracted document content for Anti-Silo triangulation review",
                    "",
                    extracted or "[no extractable text]",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        rows.append(
            {
                "source_file": rel_path.as_posix(),
                "staged_file": target.relative_to(output_vault).as_posix(),
                "extension": ext,
                "raw_source_hash": digest,
                "bytes": source.stat().st_size,
            }
        )

    payload = {
        "generated_by": GENERATED_BY,
        "generated": datetime.now(timezone.utc).isoformat(),
        "source_root": str(source_root),
        "output_vault": str(output_vault),
        "files": len(rows),
        "by_extension": by_extension,
        "rows": rows,
    }
    (output_vault / "SOURCE_MANIFEST.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    md = ["# Anti-Silo Source Intake", "", f"- source root: `{source_root}`", f"- files staged: **{len(rows)}**", ""]
    for ext, count in sorted(by_extension.items()):
        md.append(f"- `{ext}`: {count}")
    (output_vault / "SOURCE_INTAKE.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    return payload
