from __future__ import annotations

import hashlib
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .ingest_extract import extract_text


GENERATED_BY = "anti-silo ingest"
DEFAULT_INGEST_EXTENSIONS = {
    ".md",
    ".txt",
    ".csv",
    ".json",
    ".html",
    ".htm",
    ".docx",
    ".xlsx",
    ".pdf",
}


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _safe_name(rel_path: Path) -> str:
    stem = "__".join(rel_path.with_suffix("").parts)
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", stem).strip("._-")
    return f"{stem or 'source'}.md"


def _excluded(rel_path: Path, config: dict[str, Any]) -> bool:
    excluded = set(config.get("exclude_dirs", []))
    parts = set(rel_path.parts)
    return bool(parts & excluded)


def _prepare_output(source_root: Path, output_vault: Path) -> None:
    source_root = source_root.resolve()
    output_vault = output_vault.resolve()
    if output_vault == source_root:
        raise ValueError("output vault must be different from the source folder")
    if output_vault.exists():
        manifest = output_vault / "SOURCE_MANIFEST.json"
        if not manifest.exists():
            raise ValueError(f"refusing to replace non-ingest folder: {output_vault}")
        data = json.loads(manifest.read_text(encoding="utf-8"))
        if data.get("generated_by") != GENERATED_BY:
            raise ValueError(f"refusing to replace folder not generated by Anti-Silo ingest: {output_vault}")
        shutil.rmtree(output_vault)
    output_vault.mkdir(parents=True, exist_ok=True)


def iter_source_files(source_root: Path, config: dict[str, Any]) -> list[Path]:
    extensions = {ext.lower() for ext in config.get("ingest_extensions", sorted(DEFAULT_INGEST_EXTENSIONS))}
    files: list[Path] = []
    if source_root.is_file():
        return [source_root] if source_root.suffix.lower() in extensions and not source_root.name.startswith("~$") else []
    for path in source_root.rglob("*"):
        if not path.is_file() or path.name.startswith("~$"):
            continue
        rel_path = path.relative_to(source_root)
        if _excluded(rel_path, config):
            continue
        if path.suffix.lower() in extensions:
            files.append(path)
    return sorted(files)


def write_ingest(
    source_root: Path,
    config: dict[str, Any],
    output_vault: Path | None = None,
    source_links: dict[str, Path] | None = None,
) -> dict[str, Any]:
    source_root = source_root.resolve()
    output_vault = (output_vault or (source_root.parent / f"{source_root.name}_anti_silo_staging")).resolve()
    _prepare_output(source_root, output_vault)

    rows: list[dict[str, Any]] = []
    source_links = source_links or {}
    repair_sources = output_vault / "repair_sources"
    by_extension: dict[str, int] = {}
    for source in iter_source_files(source_root, config):
        rel_path = source.relative_to(source_root) if source_root.is_dir() else Path(source.name)
        digest = _sha256(source)
        ext = source.suffix.lower()
        by_extension[ext] = by_extension.get(ext, 0) + 1
        extraction = extract_text(source)
        extracted = extraction.text.strip()
        target = output_vault / _safe_name(rel_path)
        linked_source = source_links.get(rel_path.as_posix())
        linked_digest = _sha256(linked_source) if linked_source and linked_source.is_file() else ""
        intake_metadata = ["intake_kind: self_indexed"]
        claim_text = "claim: extracted document content awaiting independent source verification"
        if linked_digest:
            intake_metadata = ["repair_linked_source: true", f"source_hash: {linked_digest}"]
            claim_text = "claim: extracted document content linked to a user-selected independent source; semantic match not verified"
            repair_sources.mkdir(parents=True, exist_ok=True)
            pointer = repair_sources / f"{linked_digest}.md"
            if not pointer.exists():
                pointer.write_text(
                    "\n".join(
                        [
                            "type: user_selected_source",
                            "source_of_truth: true",
                            f"raw_source_hash: {linked_digest}",
                            f"source_name: {json.dumps(linked_source.name, ensure_ascii=False)}",
                            "---",
                            "source-of-truth: user-selected independent local file; semantic match not verified",
                            "",
                        ]
                    ),
                    encoding="utf-8",
                )
        target.write_text(
            "\n".join(
                [
                    "type: extracted_source_document",
                    "claim_kind: synthesis",
                    *intake_metadata,
                    f"extraction_status: {extraction.status}",
                    f"extraction_note: {json.dumps(extraction.note, ensure_ascii=False)}",
                    f"intake_hash: {digest}",
                    f"source_file: {json.dumps(rel_path.as_posix(), ensure_ascii=False)}",
                    f"source_extension: {ext}",
                    "---",
                    f"source-of-truth: local intake copy from `{rel_path.as_posix()}`; not independent evidence",
                    claim_text,
                    "",
                    extracted or "[no extractable text]",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        rows.append(
            {
                "source_file": rel_path.as_posix(),
                "staged_file": target.relative_to(output_vault).as_posix(),
                "extension": ext,
                "raw_source_hash": digest,
                "bytes": source.stat().st_size,
                "extraction_status": extraction.status,
                "extraction_note": extraction.note,
                "linked_source": linked_source.name if linked_digest and linked_source else "",
            }
        )

    payload = {
        "generated_by": GENERATED_BY,
        "generated": datetime.now(timezone.utc).isoformat(),
        "source_root": str(source_root),
        "output_vault": str(output_vault),
        "files": len(rows),
        "by_extension": by_extension,
        "rows": rows,
    }
    (output_vault / "SOURCE_MANIFEST.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    md = ["# Anti-Silo Source Intake", "", f"- source root: `{source_root}`", f"- files staged: **{len(rows)}**", ""]
    for ext, count in sorted(by_extension.items()):
        md.append(f"- `{ext}`: {count}")
    (output_vault / "SOURCE_INTAKE.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    return payload
